# Generated by Django 5.0 on 2023-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='captcha',
            field=models.CharField(default='', max_length=50),
        ),
    ]
